'rules':
  'no-undef': 1
  'react/jsx-no-bind': [2, { 'ignoreRefs': true }]
  'semi': [2, 'never']
  'react/jsx-filename-extension': 0

'env':
  'es6': true
  'browser': true
  'node': true

'extends': 'airbnb'
'parser': 'babel-eslint'
'plugins': ['react']

globals:
  '__DEV__': true
